In [9]:
import pandas as pd

df = pd.read_csv(r'C:\Users\PC027\Desktop\Project\KOSPO공모전\전처리 데이터\dataframe_1.csv')

In [10]:
# df 불러온 뒤,
df['현물시장거래일'] = pd.to_datetime(df['현물시장거래일'])
df['년도'] = df['현물시장거래일'].dt.year

In [14]:
RPS = pd.read_csv(r'C:\Users\PC027\Desktop\Project\KOSPO공모전\REC 예측 관련데이터\RPS 공급의무자별 의무공급량\이후 자료 (8년치)\combined_year.csv', encoding='cp949')

In [15]:
print(RPS)

      년도       구분  의무공급량(MWh)
0   2017  한국수력원자력   2,915,892
1   2017   한국남동발전   3,137,560
2   2017   한국중부발전   1,985,550
3   2017   한국서부발전   2,241,674
4   2017   한국남부발전   2,203,025
5   2017   한국동서발전   2,277,079
6   2018  한국수력원자력   3,448,994
7   2018   한국남동발전   3,862,729
8   2018   한국중부발전   2,916,317
9   2018   한국서부발전   2,598,712
10  2018   한국남부발전   2,749,321
11  2018   한국동서발전   2,786,870
12  2019  한국수력원자력   3,742,772
13  2019   한국남동발전   4,340,865
14  2019   한국중부발전   3,080,392
15  2019   한국서부발전   3,289,547
16  2019   한국남부발전   3,759,778
17  2019   한국동서발전   3,419,002
18  2020  한국수력원자력   4,815,568
19  2020   한국남동발전   5,040,384
20  2020   한국중부발전   3,597,402
21  2020   한국서부발전   3,660,845
22  2020   한국남부발전   4,039,843
23  2020   한국동서발전   4,019,422
24  2021  한국수력원자력   6,666,591
25  2021   한국남동발전   5,395,388
26  2021   한국중부발전   5,159,228
27  2021   한국서부발전   4,037,301
28  2021   한국남부발전   4,535,876
29  2021   한국동서발전   4,798,108
30  2022  한국수력원자력   9,547,185
31  2022   한국남동발전   6,609,089
32  2022   한국중부발전   7,420,869
33  2022   한국서부발전   6,852,132
34  2022   한국남부발전   7,692,343
35  2022   한국동서발전   6,630,739
36  2023  한국수력원자력  10,984,553
37  2023   한국남동발전   7,162,788
38  2023   한국중부발전   7,774,116
39  2023   한국서부발전   6,857,067
40  2023   한국남부발전   8,472,739
41  2023   한국동서발전   6,478,649
42  2024  한국수력원자력  11,596,908
43  2024   한국남동발전   6,922,425
44  2024   한국중부발전   8,304,797
45  2024   한국서부발전   7,062,062
46  2024   한국남부발전   6,813,810
47  2024   한국동서발전   6,283,884

In [16]:
RPS

      년도       구분  의무공급량(MWh)
0   2017  한국수력원자력   2,915,892
1   2017   한국남동발전   3,137,560
2   2017   한국중부발전   1,985,550
3   2017   한국서부발전   2,241,674
4   2017   한국남부발전   2,203,025
5   2017   한국동서발전   2,277,079
6   2018  한국수력원자력   3,448,994
7   2018   한국남동발전   3,862,729
8   2018   한국중부발전   2,916,317
9   2018   한국서부발전   2,598,712
10  2018   한국남부발전   2,749,321
11  2018   한국동서발전   2,786,870
12  2019  한국수력원자력   3,742,772
13  2019   한국남동발전   4,340,865
14  2019   한국중부발전   3,080,392
15  2019   한국서부발전   3,289,547
16  2019   한국남부발전   3,759,778
17  2019   한국동서발전   3,419,002
18  2020  한국수력원자력   4,815,568
19  2020   한국남동발전   5,040,384
20  2020   한국중부발전   3,597,402
21  2020   한국서부발전   3,660,845
22  2020   한국남부발전   4,039,843
23  2020   한국동서발전   4,019,422
24  2021  한국수력원자력   6,666,591
25  2021   한국남동발전   5,395,388
26  2021   한국중부발전   5,159,228
27  2021   한국서부발전   4,037,301
28  2021   한국남부발전   4,535,876
29  2021   한국동서발전   4,798,108
30  2022  한국수력원자력   9,547,185
31  2022   한국남동발전   6,609,089
32  2022   한국중부발전   7,420,869
33  2022   한국서부발전   6,852,132
34  2022   한국남부발전   7,692,343
35  2022   한국동서발전   6,630,739
36  2023  한국수력원자력  10,984,553
37  2023   한국남동발전   7,162,788
38  2023   한국중부발전   7,774,116
39  2023   한국서부발전   6,857,067
40  2023   한국남부발전   8,472,739
41  2023   한국동서발전   6,478,649
42  2024  한국수력원자력  11,596,908
43  2024   한국남동발전   6,922,425
44  2024   한국중부발전   8,304,797
45  2024   한국서부발전   7,062,062
46  2024   한국남부발전   6,813,810
47  2024   한국동서발전   6,283,884

In [17]:
# '의무공급량(MWh)' 값을 숫자로 변환 (쉼표 제거)
RPS['의무공급량(MWh)'] = RPS['의무공급량(MWh)'].replace(",","",regex=True).astype(int)

In [18]:
pivot_rec = RPS.pivot(
    index='년도',
    columns='구분',
    values='의무공급량(MWh)'
)

In [19]:
print(pivot_rec)

구분     한국남동발전   한국남부발전   한국동서발전   한국서부발전   한국수력원자력   한국중부발전
년도
2017  3137560  2203025  2277079  2241674   2915892  1985550
2018  3862729  2749321  2786870  2598712   3448994  2916317
2019  4340865  3759778  3419002  3289547   3742772  3080392
2020  5040384  4039843  4019422  3660845   4815568  3597402
2021  5395388  4535876  4798108  4037301   6666591  5159228
2022  6609089  7692343  6630739  6852132   9547185  7420869
2023  7162788  8472739  6478649  6857067  10984553  7774116
2024  6922425  6813810  6283884  7062062  11596908  8304797

In [20]:
df.columns

Index(['종가', '육지 최저가', '매수 건수', '육지 체결건수', '육지 체결물량', '육지 매도물량', '육지 매도건수',
       '육지 평균가', '총 거래건수', '육지 상한가', '현물시장거래일', '매수 물량', '육지 최고가', '육지 하한가',
       '총 거래물량', '거래금액', '순번', '육지_체결_가격_트랜드', '육지_체결_가격_주기성분', '육지_체결_건수_트랜드',
       '육지_체결_건수_주기성분', '육지_거래_규모_트랜드', '육지_거래_규모_주기성분', '년도'],
      dtype='object')

In [21]:
pivot_rec.columns = [str(col) + '_RPS' for col in pivot_rec.columns]

In [22]:
pivot_rec

      한국남동발전_RPS  한국남부발전_RPS  한국동서발전_RPS  한국서부발전_RPS  한국수력원자력_RPS  한국중부발전_RPS
년도
2017     3137560     2203025     2277079     2241674      2915892     1985550
2018     3862729     2749321     2786870     2598712      3448994     2916317
2019     4340865     3759778     3419002     3289547      3742772     3080392
2020     5040384     4039843     4019422     3660845      4815568     3597402
2021     5395388     4535876     4798108     4037301      6666591     5159228
2022     6609089     7692343     6630739     6852132      9547185     7420869
2023     7162788     8472739     6478649     6857067     10984553     7774116
2024     6922425     6813810     6283884     7062062     11596908     8304797

In [23]:
# df의 현물시장거래일로부터 년도 추출
df['현물시장거래일'] = pd.to_datetime(df['현물시장거래일'])
df['년도'] = df['현물시장거래일'].dt.year

# pivot_mwh의 인덱스 -> 컬럼
pivot_mwh = pivot_rec.reset_index()

df_merged = pd.merge(
    df,
    pivot_mwh,
    how='left',  # 필요에 따라 'inner' 등 변경
    on='년도'
)

In [24]:
df_merged

,종가,육지 최저가,매수 건수,육지 체결건수,육지 체결물량,육지 매도물량,육지 매도건수,육지 평균가,총 거래건수,육지 상한가,...,육지_체결_건수_주기성분,육지_거래_규모_트랜드,육지_거래_규모_주기성분,년도,한국남동발전_RPS,한국남부발전_RPS,한국동서발전_RPS,한국서부발전_RPS,한국수력원자력_RPS,한국중부발전_RPS
0,128000,128000,32,158,11530,245653,1556,130445,159,171600,...,35.947576,21551.242874,824.788427,2017,3137560,2203025,2277079,2241674,2915892,1985550
1,130000,125000,20,274,14899,156778,1374,130037,281,166400,...,32.787230,21648.037167,2732.524955,2017,3137560,2203025,2277079,2241674,2915892,1985550
2,133500,120000,128,588,135260,283418,1614,132362,615,169000,...,0.517604,21986.817195,10822.075069,2017,3137560,2203025,2277079,2241674,2915892,1985550
3,125500,125500,12,34,2231,185603,1259,126757,35,173500,...,-35.089336,22228.802929,15032.618951,2017,3137560,2203025,2277079,2241674,2915892,1985550
4,119000,119000,17,190,16198,192981,1190,128969,199,163100,...,-48.821082,22325.597222,15709.163003,2017,3137560,2203025,2277079,2241674,2915892,1985550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749,74700,74700,45,3834,126304,243916,5138,74856,3848,82300,...,-62.970389,143336.941945,6684.327242,2024,6922425,6813810,6283884,7062062,11596908,8304797
750,72700,72700,52,1498,90601,251886,2790,73948,1505,82100,...,-72.615687,143411.358860,7482.758375,2024,6922425,6813810,6283884,7062062,11596908,8304797
751,67200,67000,92,1010,69358,347268,2157,68733,1022,79900,...,-110.361125,143597.401148,9164.877705,2024,6922425,6813810,6283884,7062062,11596908,8304797
752,66900,66900,98,1107,67084,184940,1887,67499,1114,73900,...,-128.626703,143671.818063,9271.436211,2024,6922425,6813810,6283884,7062062,11596908,8304797
753,62100,61300,59,823,85729,260551,1620,62684,828,73500,...,-171.296081,143857.860350,6866.115741,2024,6922425,6813810,6283884,7062062,11596908,8304797

In [25]:
df_merged.to_csv(r'C:\Users\PC027\Desktop\Project\KOSPO공모전\전처리 데이터_수량증가\new_dataframe_2.csv',index=False,encoding='cp949')